/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Random;
//import static java.lang.Math.random;
//import static java.lang.StrictMath.random;
import static javax.swing.JOptionPane.*;
import objects.User;

/**
 *
 * @author Administrator
 */
public class ManageUsersFrame extends javax.swing.JFrame {
    private MainFrame mf;
    private User user;
    private int pin;//(lblPin)
    ArrayList<User> userList;

    /**
     * Creates new form ManageUsersFrame
     */
    public ManageUsersFrame() {
        initComponents();
        this.userList = user.getFullList();        
        visualConfigs(0);
    }
    
    public ManageUsersFrame(User u,MainFrame mff){
        initComponents();
        this.mf=mff;
        this.user=u;
        this.userList = user.getFullList();
        visualConfigs(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtAppTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbOperation = new javax.swing.JComboBox<>();
        pCreate = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPin = new javax.swing.JLabel();
        lblGMName = new javax.swing.JLabel();
        txtGMName = new javax.swing.JTextField();
        lblGMRank = new javax.swing.JLabel();
        jcbRank = new javax.swing.JComboBox<>();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblRemove = new javax.swing.JLabel();
        jcbGMName = new javax.swing.JComboBox<>();
        txtPin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnBackCancel = new javax.swing.JButton();
        btnProceed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        txtAppTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtAppTitle.setForeground(new java.awt.Color(255, 255, 255));
        txtAppTitle.setText("User Management");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAppTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAppTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Choose the operation:");

        jcbOperation.setForeground(new java.awt.Color(255, 255, 255));
        jcbOperation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Create", "Remove", "Update" }));
        jcbOperation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbOperationItemStateChanged(evt);
            }
        });

        lblUsername.setText("Username:");

        lblPin.setText("Pin:");

        lblGMName.setText("New GM Name:");

        lblGMRank.setText("GM Rank:");

        jcbRank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TGM", "FGM", "GMTL", "HGM", "ADMIN" }));

        lblPassword.setText("Password:");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        lblRemove.setText("GM Name:");

        jcbGMName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbGMName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbGMNameItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pCreateLayout = new javax.swing.GroupLayout(pCreate);
        pCreate.setLayout(pCreateLayout);
        pCreateLayout.setHorizontalGroup(
            pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRemove)
                    .addComponent(lblGMRank)
                    .addComponent(lblGMName)
                    .addComponent(lblPin)
                    .addComponent(lblPassword)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbGMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(txtPassword)
                    .addComponent(txtGMName)
                    .addComponent(txtPin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCreateLayout.setVerticalGroup(
            pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCreateLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRemove)
                    .addComponent(jcbGMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPin)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGMName)
                    .addComponent(txtGMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGMRank)
                    .addComponent(jcbRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 128, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        btnBackCancel.setText("Back");
        btnBackCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackCancelActionPerformed(evt);
            }
        });

        btnProceed.setText("Proceed");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProceed)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackCancel)
                    .addComponent(btnProceed))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackCancelActionPerformed
        // Cancel
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackCancelActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        switch(jcbOperation.getSelectedIndex()){
            case 0:
                createU();
                break;
            case 1:
                removeU();
                break;
            case 2:
                updateU();
                break;
        }
    }//GEN-LAST:event_btnProceedActionPerformed

    private void createU(){
        Random rand=new Random();
        String initialPin = String.format("%04d", rand.nextInt(10000));
        int pni=Integer.parseInt(initialPin);
        
        user.createUser(txtUsername.getText(),txtPassword.getText(),pni,txtGMName.getText(), jcbRank.getSelectedIndex());
        showMessageDialog(null, "User: "+txtUsername.getText()+"\nPass: "+txtPassword.getText()+"\nPin: "+pni+"\nGM Name: "+txtGMName.getText()+"\nRank: "+ jcbRank.getSelectedIndex());
        
        userList=user.getFullList();
        jcbGMName.removeAllItems();
                userList.forEach((nom) -> {
                    jcbGMName.addItem(nom.getGmName());
                });
                clearFields();
    }
    
    private void removeU(){
        user.removeUser(String.valueOf(jcbGMName.getSelectedItem()));
        userList=user.getFullList();
        jcbGMName.removeAllItems();
                userList.forEach((nom) -> {
                    jcbGMName.addItem(nom.getGmName());
                });
        
    }
    
    private void updateU(){
        String actualGMName, usr, pas, gmN;
        int pi,ran;
        actualGMName = String.valueOf(jcbGMName.getSelectedItem());
        usr=txtUsername.getText();
        pas=txtPassword.getText();
        pi=Integer.parseInt(txtPin.getText());
        ran=jcbRank.getSelectedIndex();
        gmN=txtGMName.getText();
        String opts="";
        //TODO: Ask for confirmation
        
        user.updateUser(actualGMName, usr, pas, pi, gmN, ran);
        
        userList=user.getFullList();
        jcbGMName.removeAllItems();
                userList.forEach((nom) -> {
                    jcbGMName.addItem(nom.getGmName());
                });
                clearFields();
    }
    
    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jcbOperationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbOperationItemStateChanged
        btnProceed.setText(jcbOperation.getSelectedItem().toString());
        switch(evt.getItem().toString()){
            case "Create"://Create
                visualConfigs(0);
                break;
                
            case "Remove"://Remove
                visualConfigs(1);
                break;
                
            case "Update"://Update
                visualConfigs(2);
                
                break;
        }
    }//GEN-LAST:event_jcbOperationItemStateChanged

    private void jcbGMNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbGMNameItemStateChanged
        userList.forEach((nom) -> {
                    if(nom.getGmName().equals(String.valueOf(jcbGMName.getSelectedItem()))){
                        txtUsername.setText(nom.getNombre_usuario());
                        txtPassword.setText("");
                        txtPin.setText(String.valueOf(nom.getPin_usuario()));
                        txtGMName.setText(nom.getGmName());
                        jcbRank.setSelectedIndex(nom.getUserRank());
                    }
                });
        
    }//GEN-LAST:event_jcbGMNameItemStateChanged

    private void visualConfigs(int opt){
        switch(opt){
            case 0://Create
                clearFields();
                btnProceed.setBackground(Color.green);
                txtUsername.setVisible(true);
                txtPassword.setVisible(true);
                lblUsername.setVisible(true);
                lblPassword.setVisible(true);
                lblPin.setVisible(true);
                txtGMName.setVisible(true);
                lblGMName.setVisible(true);
                lblGMRank.setVisible(true);
                lblPin.setVisible(true);
                jcbGMName.setVisible(false);
                lblRemove.setVisible(false);
                txtPin.setVisible(true);
                txtPin.setEnabled(false);
                jcbRank.setVisible(true);
                jcbRank.setEnabled(true);
                txtUsername.setEnabled(true);
                
                break;
                
            case 1://Remove
                clearFields();
                btnProceed.setBackground(Color.red);
                lblRemove.setVisible(true);
                jcbGMName.setVisible(true);
                lblGMRank.setVisible(true);
                jcbRank.setVisible(true);
                jcbRank.setEnabled(false);
                lblPassword.setVisible(false);
                txtPassword.setVisible(false);
                lblPin.setVisible(false);
                txtPin.setVisible(false);
                lblGMName.setVisible(false);
                txtGMName.setVisible(false);
                lblUsername.setVisible(true);
                txtUsername.setVisible(true);
                txtUsername.setEnabled(false);
                
                jcbGMName.removeAllItems();
                userList.forEach((nom) -> {
                    jcbGMName.addItem(nom.getGmName());
                });
                break;
                
            case 2://Update
                clearFields();
                btnProceed.setBackground(Color.yellow);
                lblUsername.setVisible(true);
                txtUsername.setVisible(true);
                txtUsername.setEnabled(true);
                lblPassword.setVisible(true);
                txtPassword.setVisible(true);
                txtPassword.setEnabled(true);
                lblPin.setVisible(true);
                txtPin.setVisible(true);
                txtPin.setEnabled(true);
                lblGMName.setVisible(true);
                txtGMName.setVisible(true);
                txtGMName.setEnabled(true);
                lblGMRank.setVisible(true);
                jcbRank.setVisible(true);
                jcbRank.setEnabled(true);
                jcbGMName.setVisible(true);
                lblRemove.setVisible(true);
                
                jcbGMName.removeAllItems();
                
                userList.forEach((nom) -> {
                    jcbGMName.addItem(nom.getGmName());
                    if(nom.getGmName().equals(String.valueOf(jcbGMName.getSelectedItem()))){
                        txtUsername.setText(nom.getNombre_usuario());
                        txtPassword.setText("");
                        txtPin.setText(String.valueOf(nom.getPin_usuario()));
                        txtGMName.setText(nom.getGmName());
                        jcbRank.setSelectedIndex(nom.getUserRank());
                    }
                });
                break;
        }
    }
    
    private void clearFields(){
        txtUsername.setText("");
        txtPassword.setText("");
        txtPin.setText("");
        txtGMName.setText("");
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackCancel;
    private javax.swing.JButton btnProceed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcbGMName;
    private javax.swing.JComboBox<String> jcbOperation;
    private javax.swing.JComboBox<String> jcbRank;
    private javax.swing.JLabel lblGMName;
    private javax.swing.JLabel lblGMRank;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblRemove;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pCreate;
    private javax.swing.JLabel txtAppTitle;
    private javax.swing.JTextField txtGMName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPin;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
